### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by gbharathkumar** [angular-university/reactive-patterns-course#1]
while trying to run the application, i am getting an error Uncaught TypeError: Cannot read property 'apply' of undefined"Cannot read property 'apply' of undefined" 
in vendor.bundle.js:35669 
I installed the modules using YARN. How to get rid of this issue.

**Comment by jhades** [comment]
Hello, I just cloned and reinstalled the master branch with yarn, and I can confirm everything is working without errors. I suggest the following: please update the angular CLI with:

    sudo npm install -g @angular/cli

And then try to do npm start again. Does this fix the issue ? 

Also, you might have accidentally the ancient CLI package installed, its was named angular-cli, this package is deprecated and its better to uninstall it.

I none of these approaches work, could you please send me:

- which branch you are running
- the full stack trace
- your node and npm versions

Thanks, Kind Regards, Vasco

**Comment by gbharathkumar** [comment]
Hi Vasco, 

Thanks for replying. I still have this issue. 
i have updated angular cli using the command npm install -g @angular/cli. There is no older version of CLI available in my machine. 

Branch name : master
node version: v6.9.1
npm version : 3.10.8
chrome version : Version 44.0.2403.157 m

stack trace details are
combine (common.es5.js:3109)
__webpack_exports__.b (common.es5.js:2959)
__webpack_require__ (bootstrap cdfb7…d20de5728a6:52)
(anonymous function) (vendor.bundle.js:74420)
__webpack_require__ (bootstrap cdfb7…d20de5728a6:52)
webpackJsonp.192 (src async:7)
__webpack_require__ (bootstrap cdfb7…d20de5728a6:52)
webpackJsonp.637 (user.service.ts:13)
__webpack_require__ (bootstrap cdfb7…d20de5728a6:52)
webpackJsonpCallback (bootstrap cdfb7…d20de5728a6:23)
(anonymous function) (main.bundle.js:1)

**Comment by gbharathkumar** [comment]
Hi, 

I could able to fix this issue. my chrome version is Version 44.0.2403.157 m which expects the polyfills to be available. Hence i uncommented the below code in polyfills.ts and imported the polyfills in main.ts

included code in main.ts
================
import './polyfills.ts';

uncommented code in polyfills.ts
====================
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';

Thanks,
